#!/usr/bin/env node

/**
 * scripts/generate_api.mjs
 * 
 * 真実の唯一のソース (SSoT) である `shared/schema/` (TypeScript + Zod) から
 * Swift Codable モデル: ios/Sources/Models/Generated/APISchemas.generated.swift
 * を直接自動生成します。
 * 
 * サーバー側 (TypeScript) は shared/schema/*.ts から z.infer を直接参照するため、
 * 中間ディレクトリ shared/api/* は作成・保持しません。
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as schemas from "../shared/schema/index.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = resolve(__dirname, "..");

const SWIFT_OUTPUT_DIR = resolve(ROOT_DIR, "ios/Sources/Models/Generated");

// ==========================================
// 1. Zod 型解析ヘルパー
// ==========================================
function unwrapZodType(schema) {
  let current = schema;
  let isOptional = false;

  while (current) {
    const typeName = current._def?.typeName;
    if (typeName === "ZodOptional" || typeName === "ZodDefault") {
      isOptional = true;
      current = current._def.innerType;
    } else {
      break;
    }
  }

  return { unwrapped: current, isOptional };
}

function resolveSwiftType(schema) {
  const def = schema._def;
  if (def.refComponent) {
    return def.refComponent;
  }

  const { unwrapped } = unwrapZodType(schema);
  const typeName = unwrapped._def.typeName;

  if (typeName === "ZodString") return "String";
  if (typeName === "ZodBoolean") return "Bool";
  if (typeName === "ZodNumber") return "Double";
  if (typeName === "ZodArray") {
    const itemType = resolveSwiftType(unwrapped._def.type);
    return `[${itemType}]`;
  }
  if (typeName === "ZodObject") {
    return "AnyCodable";
  }
  return "AnyCodable";
}

function generateSwiftModels() {
  // 1. shared/schema からエクスポートされた Zod スキーマ群（*Schema）を動的走査
  const registeredSchemas = {};
  for (const [exportName, item] of Object.entries(schemas)) {
    if (exportName.endsWith("Schema") && typeof item?.safeParse === "function") {
      const schemaName = exportName.replace(/Schema$/, "");
      registeredSchemas[schemaName] = item;
    }
  }

  // 2. Swift Codable モデル生成
  let swiftContent = `// Code generated by scripts/generate_api.mjs from shared/schema/ (Zod SSoT). DO NOT EDIT.
import Foundation

`;

  for (const [schemaName, schema] of Object.entries(registeredSchemas)) {
    swiftContent += `public struct ${schemaName}: Codable, Sendable {\n`;
    const shape = schema._def.shape ? schema._def.shape() : {};
    const propList = Object.entries(shape);

    for (const [propName, propSchema] of propList) {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema);
      if (isOptional) {
        swiftContent += `    public var ${propName}: ${swiftType}?\n`;
      } else {
        swiftContent += `    public var ${propName}: ${swiftType}\n`;
      }
    }

    // イニシャライザ
    swiftContent += `\n    public init(\n`;
    const initParams = propList.map(([propName, propSchema]) => {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema);
      return isOptional
        ? `        ${propName}: ${swiftType}? = nil`
        : `        ${propName}: ${swiftType}`;
    });
    swiftContent += initParams.join(",\n") + `\n    ) {\n`;

    for (const [propName] of propList) {
      swiftContent += `        self.${propName} = ${propName}\n`;
    }
    swiftContent += `    }\n`;
    swiftContent += `}\n\n`;
  }

  mkdirSync(SWIFT_OUTPUT_DIR, { recursive: true });
  writeFileSync(join(SWIFT_OUTPUT_DIR, "APISchemas.generated.swift"), swiftContent, "utf-8");
  console.log(`✅ [Swift] Codable モデル生成完了: ios/Sources/Models/Generated/APISchemas.generated.swift (${Object.keys(registeredSchemas).length} スキーマ)`);
}

generateSwiftModels();
