#!/usr/bin/env node

/**
 * scripts/generate_api.mjs
 * 
 * 真実の唯一のソース (SSoT) である `shared/schema/` (TypeScript + Zod) から
 * 1. TypeScript API 型定義: shared/api/generated/schema.ts
 * 2. Swift Codable モデル: ios/Sources/Models/Generated/APISchemas.generated.swift
 * を直接一括自動生成します。
 * 
 * 個別モデルのデータ・フィールド名は一切持たず、すべて動的にスキーマを走査します。
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as schemas from "../shared/schema/index.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = resolve(__dirname, "..");

const TS_OUTPUT_DIR = resolve(ROOT_DIR, "shared/api/generated");
const SWIFT_OUTPUT_DIR = resolve(ROOT_DIR, "ios/Sources/Models/Generated");

// ==========================================
// 1. Zod 型解析ヘルパー
// ==========================================
function unwrapZodType(schema) {
  let current = schema;
  let isOptional = false;

  while (current) {
    const typeName = current._def?.typeName;
    if (typeName === "ZodOptional" || typeName === "ZodDefault") {
      isOptional = true;
      current = current._def.innerType;
    } else {
      break;
    }
  }

  return { unwrapped: current, isOptional };
}

function resolveTsType(schema) {
  const def = schema._def;
  if (def.refComponent) {
    return def.refComponent;
  }

  const { unwrapped } = unwrapZodType(schema);
  const typeName = unwrapped._def.typeName;

  if (typeName === "ZodString") return "string";
  if (typeName === "ZodBoolean") return "boolean";
  if (typeName === "ZodNumber") return "number";
  if (typeName === "ZodArray") {
    const itemType = resolveTsType(unwrapped._def.type);
    return `${itemType}[]`;
  }
  if (typeName === "ZodObject") {
    // 参照コンポーネントがなければインラインまたは unknown
    return "Record<string, unknown>";
  }
  return "unknown";
}

function resolveSwiftType(schema) {
  const def = schema._def;
  if (def.refComponent) {
    return def.refComponent;
  }

  const { unwrapped } = unwrapZodType(schema);
  const typeName = unwrapped._def.typeName;

  if (typeName === "ZodString") return "String";
  if (typeName === "ZodBoolean") return "Bool";
  if (typeName === "ZodNumber") return "Double";
  if (typeName === "ZodArray") {
    const itemType = resolveSwiftType(unwrapped._def.type);
    return `[${itemType}]`;
  }
  if (typeName === "ZodObject") {
    return "AnyCodable";
  }
  return "AnyCodable";
}

function generateAll() {
  // 1. shared/schema からエクスポートされた Zod スキーマ群（*Schema）を動的走査
  const registeredSchemas = {};
  for (const [exportName, item] of Object.entries(schemas)) {
    if (exportName.endsWith("Schema") && typeof item?.safeParse === "function") {
      const schemaName = exportName.replace(/Schema$/, "");
      registeredSchemas[schemaName] = item;
    }
  }

  // 2. TypeScript 型定義生成
  let tsContent = `// Code generated by scripts/generate_api.mjs from shared/schema/ (Zod SSoT). DO NOT EDIT.\n\n`;
  for (const [schemaName, schema] of Object.entries(registeredSchemas)) {
    tsContent += `export interface ${schemaName} {\n`;
    const shape = schema._def.shape ? schema._def.shape() : {};

    for (const [propName, propSchema] of Object.entries(shape)) {
      const { isOptional } = unwrapZodType(propSchema);
      const tsType = resolveTsType(propSchema);
      const optional = isOptional ? "?" : "";
      tsContent += `  ${propName}${optional}: ${tsType};\n`;
    }
    tsContent += `}\n\n`;
  }

  mkdirSync(TS_OUTPUT_DIR, { recursive: true });
  writeFileSync(join(TS_OUTPUT_DIR, "schema.ts"), tsContent, "utf-8");
  console.log(`✅ [TypeScript] 型定義生成完了: shared/api/generated/schema.ts`);

  // shared/api/index.ts 同期
  const tsIndex = `// shared/api/index.ts
// shared/schema/ (Zod SSoT) から自動生成された TypeScript API 型定義のエクスポート

export * from "./generated/schema";
`;
  writeFileSync(resolve(ROOT_DIR, "shared/api/index.ts"), tsIndex, "utf-8");

  // 3. Swift Codable モデル生成
  let swiftContent = `// Code generated by scripts/generate_api.mjs from shared/schema/ (Zod SSoT). DO NOT EDIT.
import Foundation

`;

  for (const [schemaName, schema] of Object.entries(registeredSchemas)) {
    swiftContent += `public struct ${schemaName}: Codable, Sendable {\n`;
    const shape = schema._def.shape ? schema._def.shape() : {};
    const propList = Object.entries(shape);

    for (const [propName, propSchema] of propList) {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema);
      if (isOptional) {
        swiftContent += `    public var ${propName}: ${swiftType}?\n`;
      } else {
        swiftContent += `    public var ${propName}: ${swiftType}\n`;
      }
    }

    // イニシャライザ
    swiftContent += `\n    public init(\n`;
    const initParams = propList.map(([propName, propSchema]) => {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema);
      return isOptional
        ? `        ${propName}: ${swiftType}? = nil`
        : `        ${propName}: ${swiftType}`;
    });
    swiftContent += initParams.join(",\n") + `\n    ) {\n`;

    for (const [propName] of propList) {
      swiftContent += `        self.${propName} = ${propName}\n`;
    }
    swiftContent += `    }\n`;
    swiftContent += `}\n\n`;
  }

  mkdirSync(SWIFT_OUTPUT_DIR, { recursive: true });
  writeFileSync(join(SWIFT_OUTPUT_DIR, "APISchemas.generated.swift"), swiftContent, "utf-8");
  console.log(`✅ [Swift] Codable モデル生成完了: ios/Sources/Models/Generated/APISchemas.generated.swift`);

  console.log(`🎉 [SSoT: Zod -> TS & Swift] すべてのコード生成が完了しました (${Object.keys(registeredSchemas).length} スキーマ)！`);
}

generateAll();
