#!/usr/bin/env node

/**
 * scripts/generate_api.mjs
 *
 * 真実の唯一のソース (SSoT) である `shared/schema/` (TypeScript + Zod 4) から
 * Swift Codable モデル: ios/Sources/Models/Generated/APISchemas.generated.swift
 * を直接自動生成します。
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as schemas from "../shared/schema/index.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = resolve(__dirname, "..");

const SWIFT_OUTPUT_DIR = resolve(ROOT_DIR, "ios/Sources/Models/Generated");

// ==========================================
// 1. Zod 4 型解析ヘルパー
// ==========================================
function unwrapZodType(schema) {
  let current = schema;
  let isOptional = false;
  let ref = current?.meta?.()?.ref;

  while (current) {
    if (!ref && current?.meta?.()?.ref) {
      ref = current.meta().ref;
    }
    if (current.type === "optional" || current.type === "nullable" || current.type === "default") {
      isOptional = true;
      current = current.unwrap();
    } else {
      break;
    }
  }

  if (!ref && current?.meta?.()?.ref) {
    ref = current.meta().ref;
  }

  return { unwrapped: current, isOptional, ref };
}

function findRegisteredSchemaName(schema, registeredSchemas) {
  for (const [name, reg] of Object.entries(registeredSchemas)) {
    if (
      schema === reg ||
      (schema.def && reg.def && schema.def === reg.def) ||
      (schema.shape && reg.shape && schema.shape === reg.shape)
    ) {
      return name;
    }
  }
  return null;
}

function resolveSwiftType(schema, registeredSchemas = {}) {
  const { unwrapped, ref } = unwrapZodType(schema);
  if (ref) {
    return ref;
  }

  // 登録済みスキーマ（SendMessagePayloadSchema 等）が直接埋め込まれている場合は自動解決
  const matchedName = findRegisteredSchemaName(unwrapped, registeredSchemas);
  if (matchedName) {
    return matchedName;
  }

  switch (unwrapped.type) {
    case "string":
      return "String";
    case "boolean":
      return "Bool";
    case "number":
      return "Double";
    case "array": {
      const itemType = resolveSwiftType(unwrapped.element, registeredSchemas);
      return `[${itemType}]`;
    }
    case "record": {
      const valType = resolveSwiftType(unwrapped.valueType, registeredSchemas);
      return `[String: ${valType}]`;
    }
    case "object":
      return "AnyCodable";
    default:
      return "AnyCodable";
  }
}

function generateSwiftModels() {
  // 1. shared/schema からエクスポートされた Zod 4 スキーマ群（*Schema）を走査
  const registeredSchemas = {};
  for (const [exportName, item] of Object.entries(schemas)) {
    if (exportName.endsWith("Schema") && typeof item?.safeParse === "function") {
      const schemaName = exportName.replace(/Schema$/, "");
      registeredSchemas[schemaName] = item;
    }
  }

  // 2. Swift Codable モデル生成
  let swiftContent = `// Code generated by scripts/generate_api.mjs from shared/schema/ (Zod SSoT). DO NOT EDIT.
import Foundation

`;

  for (const [schemaName, schema] of Object.entries(registeredSchemas)) {
    swiftContent += `public struct ${schemaName}: Codable, Sendable {\n`;
    const shape = schema.shape || {};
    const propList = Object.entries(shape);

    for (const [propName, propSchema] of propList) {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema, registeredSchemas);
      if (isOptional) {
        swiftContent += `    public var ${propName}: ${swiftType}?\n`;
      } else {
        swiftContent += `    public var ${propName}: ${swiftType}\n`;
      }
    }

    // イニシャライザ
    swiftContent += `\n    public init(\n`;
    const initParams = propList.map(([propName, propSchema]) => {
      const { isOptional } = unwrapZodType(propSchema);
      const swiftType = resolveSwiftType(propSchema, registeredSchemas);
      return isOptional
        ? `        ${propName}: ${swiftType}? = nil`
        : `        ${propName}: ${swiftType}`;
    });
    swiftContent += initParams.join(",\n") + `\n    ) {\n`;

    for (const [propName] of propList) {
      swiftContent += `        self.${propName} = ${propName}\n`;
    }
    swiftContent += `    }\n`;
    swiftContent += `}\n\n`;
  }

  mkdirSync(SWIFT_OUTPUT_DIR, { recursive: true });
  writeFileSync(join(SWIFT_OUTPUT_DIR, "APISchemas.generated.swift"), swiftContent, "utf-8");
  console.log(`✅ [Swift] Codable モデル生成完了: ios/Sources/Models/Generated/APISchemas.generated.swift (${Object.keys(registeredSchemas).length} スキーマ)`);
}

generateSwiftModels();
